config/routes.rb
Rails.application.routes.draw do
  get 'landings/index'

  resources :timelines

  resources :sequences

  resources :events

  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords"}, skip: [:sessions, :registrations]

  root 'landings#index'

  
  devise_scope :user do
    get    "login"   => "users/sessions#new",         as: :new_user_session
    post   "login"   => "users/sessions#create",      as: :user_session
    delete "signout" => "users/sessions#destroy",     as: :destroy_user_session
    
    get    "signup"  => "users/registrations#new",    as: :new_user_registration
    post   "signup"  => "users/registrations#create", as: :user_registration
    put    "signup"  => "users/registrations#update", as: :update_user_registration
    get    "account" => "users/registrations#edit",   as: :edit_user_registration
  end

end

app/models/sequence.rb
class Sequence < ActiveRecord::Base
  belongs_to :timeline
  has_many :events
end

app/controllers/sequences_controller.rb
class SequencesController < ApplicationController
  before_action :set_sequence, only: [:show, :edit, :update, :destroy]

  # GET /sequences
  # GET /sequences.json
  def index
    @sequences = Sequence.all
  end

  # GET /sequences/1
  # GET /sequences/1.json
  def show
  end

  # GET /sequences/new
  def new
    @sequence = Sequence.new
  end

  # GET /sequences/1/edit
  def edit
  end

  # POST /sequences
  # POST /sequences.json
  def create
    @sequence = Sequence.new(sequence_params)

    respond_to do |format|
      if @sequence.save
        format.html { redirect_to @sequence, notice: 'Sequence was successfully created.' }
        format.json { render :show, status: :created, location: @sequence }
      else
        format.html { render :new }
        format.json { render json: @sequence.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sequences/1
  # PATCH/PUT /sequences/1.json
  def update
    respond_to do |format|
      if @sequence.update(sequence_params)
        format.html { redirect_to @sequence, notice: 'Sequence was successfully updated.' }
        format.json { render :show, status: :ok, location: @sequence }
      else
        format.html { render :edit }
        format.json { render json: @sequence.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sequences/1
  # DELETE /sequences/1.json
  def destroy
    @sequence.destroy
    respond_to do |format|
      format.html { redirect_to sequences_url, notice: 'Sequence was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sequence
      @sequence = Sequence.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sequence_params
      params.require(:sequence).permit(:timeline_id, :name, :description, :start_datetime, :end_datetime, :priority)
    end
end

app/helpers/sequences_helper.rb
module SequencesHelper
end

app/views/sequences/_form.html.erb
<%= form_for @sequence, :html => { :class => 'form-horizontal form-model' } do |f| %>
  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :name, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :description, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_area :description, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :start_datetime, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.datetime_select :start_datetime, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :end_datetime, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.datetime_select :end_datetime, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :priority, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.number_field :priority, :class => 'text-field form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class='col-md-offset-2 col-md-10'>
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  sequences_path, :class => 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/sequences/edit.html.erb
<%- model_class = Sequence -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => Sequence %></h1>
</div>
<%= render :partial => 'form' %>

app/views/sequences/index.html.erb
<%- model_class = Sequence -%>
<div class="page-header">
  <h1><%=t '.title', :default => Sequence %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:start_datetime) %></th>
      <th><%= model_class.human_attribute_name(:end_datetime) %></th>
      <th><%= model_class.human_attribute_name(:priority) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @sequences.each do |sequence| %>
      <tr>
        <td><%= sequence.id %></td>
        <td><%= sequence.name %></td>
        <td><%= sequence.description %></td>
        <td><%= sequence.start_datetime %></td>
        <td><%= sequence.end_datetime %></td>
        <td><%= sequence.priority %></td>
        <td><%=l sequence.created_at, format: :long %></td>
        <td>
          <%= link_to sequence_path(sequence), :class => 'btn btn-xs', :title => "#{ t('.show', :default => t('helpers.links.show')) }" do %>
            <%= glyph 'info-sign' %>
            <%= glyph 'pencil' %>
          <%- end -%>
          <%= link_to sequence_path(sequence), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs', :title => "#{ t('.destroy', :default => t('helpers.links.destroy')) }" do %>
            <%= glyph 'remove' %>
          <%- end -%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_sequence_path,
            :class => 'btn btn-primary' %>

app/views/sequences/new.html.erb
<%- model_class = Sequence -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => Sequence %></h1>
</div>
<%= render :partial => 'form' %>

app/views/sequences/show.html.erb
<%- model_class = Sequence -%>
<div class="page-header">
  <h1><%=t '.title', :default => Sequence %></h1>
</div>

<div class="fieldset">
  <dl>
      <dt class="label label-default"><%= model_class.human_attribute_name(:name) %></dt>
      <dd><pre class="prettyprint"><%= @sequence.name %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:description) %></dt>
      <dd><pre class="prettyprint"><%= @sequence.description %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:start_datetime) %></dt>
      <dd><pre class="prettyprint"><%= @sequence.start_datetime %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:end_datetime) %></dt>
      <dd><pre class="prettyprint"><%= @sequence.end_datetime %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:priority) %></dt>
      <dd><pre class="prettyprint"><%= @sequence.priority %></pre></dd>
  </dl>
</div>

<div class="form-group">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              sequences_path, :class => 'btn btn-default'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_sequence_path(@sequence), :class => 'btn btn-default' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              sequence_path(@sequence),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>